apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-nrf-conf
data:
  nrfcfg.conf: |
    info:
      version: 1.0.0
      description: NRF initial local configuration

    configuration:
      MongoDBName: "free5gc"
      MongoDBUrl: "mongodb://db:27017"
      DefaultServiceIP: "0.0.0.0"
      sbi:
        scheme: http
        ipv4Addr: 0.0.0.0
        port: 29510
      DefaultPlmnId:
        mcc: "208"
        mnc: "93"
      serviceNameList:
        - nnrf-nfm
        - nnrf-disc 
