apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: free5gc-udm
  name: free5gc-udm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: free5gc-udm
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/privnet: "true"
        io.kompose.service: free5gc-udm
    spec:
      containers:
      - args:
        - ./udm
        - -udmcfg
        - ../config/udmcfg.conf
        env:
        - name: GIN_MODE
          value: release
        image: 95.217.176.245:8082/dtdocker/free5gc-udm:1.0
        imagePullPolicy: "IfNotPresent"
        name: udm
        ports:
        - containerPort: 29503
        resources: {}
        volumeMounts:
        - mountPath: /free5gc/config/free5GC.conf
          name: cfgmap0
          subPath: free5GC.conf
        - mountPath: /free5gc/config/udmcfg.conf
          name: cfgmap1
          subPath: udmcfg.conf
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: free5gc-udm-claim0
        persistentVolumeClaim:
          claimName: free5gc-udm-claim0
      - name: free5gc-udm-claim1
        persistentVolumeClaim:
          claimName: free5gc-udm-claim1
      - name: cfgmap0
        configMap:
          name: free5gc-conf
      - name: cfgmap1
        configMap:
          name: free5gc-udm-conf
status: {}
