apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-n3iwf-conf
  namespace: 5gtest
data:
  n3iwfcfg.conf: |
    info:
      version: 1.0.0
      description: N3IWF initial local configuration

    configuration:
      N3IWFInformation:
        GlobalN3IWFID:
          PLMNID:
            MCC: 208
            MNC: 93
          N3IWFID: 135
        Name:
          fN3IWF
        SupportedTAList:
          - TAC: 1
            BroadcastPLMNList:
              - PLMNID:
                  MCC: 208
                  MNC: 93
                TAISliceSupportList:
                  - SNSSAI:
                      SST: 1
                      SD: 010203
                  - SNSSAI:
                      SST: 1
                      SD: 112233
      AMFSCTPAddresses:
        - IP:
          - amf

      # Bind Interfaces
      # IKE interface
      IKEBindAddress: 0.0.0.0
      # IPSec virtual interface
      IPSecInterfaceAddress: 0.0.0.0
      # IPSec virtual interface mark
      IPSecInterfaceMark: 5
      # GTP interface
      GTPBindAddress: 0.0.0.0

      # NAS TCP Listen Port
      NASTCPPort: 20000

      # N3IWF FQDN
      FQDN: n3iwf.free5gc.org

      # Security
      # Private Key File Path
      PrivateKey:
      # Certificate Authority (CA)
      CertificateAuthority:
      # Certificate
      Certificate:

      # IP address that will be allocated to UE in IPSec tunnel
      UEIPAddressRange: 10.0.0.0/24
