apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: free5gc-nssf
  name: free5gc-nssf
  namespace: 5gcore
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: free5gc-nssf
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/privnet: "true"
        io.kompose.service: free5gc-nssf
    spec:
      containers:
      - args:
        - ./nssf
        - -nssfcfg
        - ../config/nssfcfg.conf
        env:
        - name: GIN_MODE
          value: release
        image: 95.217.176.245:8082/dtdocker/free5gc-nssf:1.0
        imagePullPolicy: "IfNotPresent"
        name: nssf
        ports:
        - containerPort: 29531
        resources: {}
        volumeMounts:
        - mountPath: /free5gc/config/nssfcfg.conf
          name: cfgmap0
          subPath: nssfcfg.conf
        - mountPath: /free5gc/config/free5GC.conf
          name: cfgmap1
          subPath: free5GC.conf
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: free5gc-nssf-claim0
        persistentVolumeClaim:
          claimName: free5gc-nssf-claim0
      - name: free5gc-nssf-claim1
        persistentVolumeClaim:
          claimName: free5gc-nssf-claim1
      - name: cfgmap0
        configMap:
                name: free5gc-nssf-conf
      - name: cfgmap1
        configMap:
           name: free5gc-conf
status: {}
